services:
  postgres:
    container_name: postgres-cart
    image: postgres:16
    ports:
      - "9100:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    expose:
      - 9100
    volumes:
      - cart-volume:/var/lib/postgresql/data
volumes:
  cart-volume:
