version: '3.8'

services:
  order-service-postgres:
    container_name: order-service-postgres
    image: postgres:16
    ports:
      - "9008:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=orderDB
    expose:
      - 9008
    volumes:
      - order-volume:/var/lib/postgresql/data
volumes:
  order-volume:
