version: '3.8'

services:
  postgres:
    container_name: postgres-product-review
    image: postgres:16
    ports:
      - "9010:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    expose:
      - 9010
    volumes:
      - product-review-volume:/var/lib/postgresql/data
volumes:
  product-review-volume:
