version: '3.8'

services:
  postgres:
    container_name: postgres-shop
    image: postgres:16
    ports:
      - "9113:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    expose:
      - 9113
    volumes:
      - shop-volume:/var/lib/postgresql/data
volumes:
  shop-volume:
