services:
  postgres-ticket:
    container_name: postgres-ticket
    image: postgres:16
    ports:
      - "9114:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    expose:
      - 9114
    volumes:
      - ticket-volume:/var/lib/postgresql/data
volumes:
  ticket-volume:
