version: '3.8'

services:
  postgres:
    container_name: postgres-product
    image: postgres:16
    ports:
      - "9011:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    expose:
      - 9011
    volumes:
      - product-volume:/var/lib/postgresql/data
volumes:
  product-volume:
