version: '3.8'

services:
  postgres:
    container_name: postgres-discount
    image: postgres:16
    ports:
      - "9104:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    expose:
      - 9104
    volumes:
      - discount-volume:/var/lib/postgresql/data
volumes:
  discount-volume:
